### ISSUE TITLE
Validate agricultural production from weather and irrigation

### ISSUE THREAD

**Issue by jrising** [AmericasWater/operational-problem#3]
Compare predicted and actual across whole US.

**Comment by ulall** [comment]
from the simulation you and Naresh set up statistically or from the
optimization model with parameters /constraints appropriately frozen?

On Wed, Jul 13, 2016 at 11:05 AM, James Rising notifications@github.com
wrote:

> Compare predicted and actual across whole US.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/AmericasWater/operational-problem/issues/3, or mute
> the thread
> https://github.com/notifications/unsubscribe/AE3cO4BouEIdPC4Ct4zr-7IFfnKdeCInks5qVP7NgaJpZM4JLhMv
> .

## 

Upmanu Lall
Alan & Carol Silberstein Professor of Engineering,
Dept. of Earth & Environmental Engineering
Dept. of Civil Eng. & Eng. Mechanics
Director, Columbia Water Center
Senior Research Scientist, International Research Institute for Climate &
Society
842F Mudd
Columbia University
500 W 120th Street
New York, NY 10027

http://www.columbia.edu/~ula2/
http://water.columbia.edu/
http://bigthink.com/users/upmanulall

**Comment by jrising** [comment]
Our task here is to use feed the outputs of the optimization model back into the Naresh and my statistical relationship to get out yields (which the model does, but I want to do it "by hand") and then compare county-by-county yields or production to actual yields or production.  I want to make sure that differences between these are fully explained by choices in the optimization to irrigate more and change agricultural land.

**Comment by ulall** [comment]
ok -- sounds like a good idea -- but if your R^2 is 0.8 or some # obviously
validation implies that the error distribution is consistent with the
variance originally explained

On Thu, Jul 14, 2016 at 12:42 PM, James Rising notifications@github.com
wrote:

> Our task here is to use feed the outputs of the optimization model back
> into the Naresh and my statistical relationship to get out yields (which
> the model does, but I want to do it "by hand") and then compare
> county-by-county yields or production to actual yields or production. I
> want to make sure that differences between these are fully explained by
> choices in the optimization to irrigate more and change agricultural land.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/AmericasWater/operational-problem/issues/3#issuecomment-232721906,
> or mute the thread
> https://github.com/notifications/unsubscribe/AE3cO-u89LBi5cy8a5sTGJ2sXHdWweNDks5qVmbtgaJpZM4JLhMv
> .

## 

Upmanu Lall
Alan & Carol Silberstein Professor of Engineering,
Dept. of Earth & Environmental Engineering
Dept. of Civil Eng. & Eng. Mechanics
Director, Columbia Water Center
Senior Research Scientist, International Research Institute for Climate &
Society
842F Mudd
Columbia University
500 W 120th Street
New York, NY 10027

http://www.columbia.edu/~ula2/
http://water.columbia.edu/
http://bigthink.com/users/upmanulall

**Comment by jrising** [comment]
Okay, I've incorporated the new Bayesian estimates, the temperature effects, and added "untracked" irrigation.  It still doesn't look great, but we aren't actually capturing much of the variance.
