### ISSUE TITLE
Optimization over individual climate runs

### ISSUE THREAD

**Issue by jrising** [AmericasWater/operational-problem#5]
Laureline is working on this.

**Comment by ulall** [comment]
will check but I think the formulation for Pernambuco handles this

On Wed, Jul 13, 2016 at 11:08 AM, James Rising notifications@github.com
wrote:

> Laureline is working on this.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/AmericasWater/operational-problem/issues/5, or mute
> the thread
> https://github.com/notifications/unsubscribe/AE3cO387AL3kTNh1vmYYmNQxvCe5XdjXks5qVP9lgaJpZM4JLhXa
> .

## 

Upmanu Lall
Alan & Carol Silberstein Professor of Engineering,
Dept. of Earth & Environmental Engineering
Dept. of Civil Eng. & Eng. Mechanics
Director, Columbia Water Center
Senior Research Scientist, International Research Institute for Climate &
Society
842F Mudd
Columbia University
500 W 120th Street
New York, NY 10027

http://www.columbia.edu/~ula2/
http://water.columbia.edu/
http://bigthink.com/users/upmanulall

**Comment by jrising** [comment]
Yes, that's my understanding.  But it isn't the model yet.

**Comment by ulall** [comment]
ok

On Thu, Jul 14, 2016 at 1:38 PM, James Rising notifications@github.com
wrote:

> Yes, that's my understanding. But it isn't the model yet.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/AmericasWater/operational-problem/issues/5#issuecomment-232736880,
> or mute the thread
> https://github.com/notifications/unsubscribe/AE3cO1ImfM5N1wpE8hK_bIX1_c-pDIhyks5qVnP4gaJpZM4JLhXa
> .

## 

Upmanu Lall
Alan & Carol Silberstein Professor of Engineering,
Dept. of Earth & Environmental Engineering
Dept. of Civil Eng. & Eng. Mechanics
Director, Columbia Water Center
Senior Research Scientist, International Research Institute for Climate &
Society
842F Mudd
Columbia University
500 W 120th Street
New York, NY 10027

http://www.columbia.edu/~ula2/
http://water.columbia.edu/
http://bigthink.com/users/upmanulall

**Comment by LaurelineJ** [comment]
I am currently working on a script "optimize-allocation.jl" that treats all demands exogenous and where climate determines how much water can be withdrawn from the surface water system. The rest is supplied by groundwater (and the super source if needed). The optimization is performed for two timesteps of six months (so for a year) while simulation of subsurface flow is at the monthly interval (for a more accurate simulation of lateral flows).

The second step will be to have two classes of water quality (higher quality for urban demand), in which case it might be cheaper to get water from the subsurface. Constraints on groundwater level will then be important to predict when domestic water is supplied by surface water (eg. water table/saline intrusion prevents groundwater extraction in New York City counties).

Does that fit what you had in mind James ?

**Comment by jrising** [comment]
Is `optimize-allocation.jl` an extension of `optimize-surface.jl`?  It sounds like it's doing the same thing for now.  If so, can you just add the additional constraints and logic to `optimize-surface`, with some configuration settings to choose between them?

The two classes of water quality is going to be a great addition!

**Comment by LaurelineJ** [comment]
Is there a way to move this issue (and the whole historic) to AWASH ?

**Comment by jrising** [comment]
Yes.  https://github.com/IQAndreas/github-issues-import

I had been avoiding doing it, to minimize email spam.
- James

**Comment by ulall** [comment]
Please call me 630 am in meeting till then and will leave for home around
then unless you are here
