### ISSUE TITLE
Improve data behind the reservoir model

### ISSUE THREAD

**Issue by jrising** [AmericasWater/operational-problem#7]
Also select reservoirs based on the configuration `timestep`.  Ipsita is working on this.

**Comment by ulall** [comment]
what do we have at the moment?
I can talk to USBR and USACE people to get data on any things you are
looking for

On Wed, Jul 13, 2016 at 11:15 AM, James Rising notifications@github.com
wrote:

> Also select reservoirs based on the configuration timestep.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/AmericasWater/operational-problem/issues/7, or mute
> the thread
> https://github.com/notifications/unsubscribe/AE3cOwvW12TPJJ6XS5xrdfKacnRNHzX2ks5qVQEIgaJpZM4JLh1n
> .

## 

Upmanu Lall
Alan & Carol Silberstein Professor of Engineering,
Dept. of Earth & Environmental Engineering
Dept. of Civil Eng. & Eng. Mechanics
Director, Columbia Water Center
Senior Research Scientist, International Research Institute for Climate &
Society
842F Mudd
Columbia University
500 W 120th Street
New York, NY 10027

http://www.columbia.edu/~ula2/
http://water.columbia.edu/
http://bigthink.com/users/upmanulall

**Comment by jrising** [comment]
We have Naresh's database of dams, but it's not used in the model.  We just have dummy data to describe reservoir minimum, maximum, and baseline storage levels (those are the three that we need).

**Comment by ulall** [comment]
ok

On Thu, Jul 14, 2016 at 1:40 PM, James Rising notifications@github.com
wrote:

> We have Naresh's database of dams, but it's not used in the model. We just
> have dummy data to describe reservoir minimum, maximum, and baseline
> storage levels (those are the three that we need).
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/AmericasWater/operational-problem/issues/7#issuecomment-232737609,
> or mute the thread
> https://github.com/notifications/unsubscribe/AE3cO1KBh32FicxoPr_H0lkIrQS8kjheks5qVnSMgaJpZM4JLh1n
> .

## 

Upmanu Lall
Alan & Carol Silberstein Professor of Engineering,
Dept. of Earth & Environmental Engineering
Dept. of Civil Eng. & Eng. Mechanics
Director, Columbia Water Center
Senior Research Scientist, International Research Institute for Climate &
Society
842F Mudd
Columbia University
500 W 120th Street
New York, NY 10027

http://www.columbia.edu/~ula2/
http://water.columbia.edu/
http://bigthink.com/users/upmanulall

**Comment by jrising** [comment]
Moved over to AWASH.
